<a href="https://colab.research.google.com/github/quocthang0507/VietnameseNaturalLanguageProcessing/blob/main/Bert_base_multilingual_cased.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://huggingface.co/bert-base-multilingual-cased

Citation: 
```
@article{DBLP:journals/corr/abs-1810-04805,
  author    = {Jacob Devlin and
               Ming{-}Wei Chang and
               Kenton Lee and
               Kristina Toutanova},
  title     = {{BERT:} Pre-training of Deep Bidirectional Transformers for Language
               Understanding},
  journal   = {CoRR},
  volume    = {abs/1810.04805},
  year      = {2018},
  url       = {http://arxiv.org/abs/1810.04805},
  archivePrefix = {arXiv},
  eprint    = {1810.04805},
  timestamp = {Tue, 30 Oct 2018 20:39:56 +0100},
  biburl    = {https://dblp.org/rec/journals/corr/abs-1810-04805.bib},
  bibsource = {dblp computer science bibliography, https://dblp.org}
}
```

In [ ]:
!pip install transformers

     |████████████████████████████████| 2.6 MB 3.9 MB/s 
     |████████████████████████████████| 895 kB 29.7 MB/s 
     |████████████████████████████████| 636 kB 43.8 MB/s 
     |████████████████████████████████| 3.3 MB 49.6 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
from transformers import BertTokenizer, TFBertModel

In [ ]:
model = TFBertModel.from_pretrained("bert-base-multilingual-cased")

Some layers from the model checkpoint at bert-base-multilingual-cased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-multilingual-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [ ]:
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

In [ ]:
text = "Xin chào các bạn tân sinh viên."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)

In [ ]:
print(output)

TFBaseModelOutputWithPooling(last_hidden_state=<tf.Tensor: shape=(1, 13, 768), dtype=float32, numpy=
array([[[-0.26800033,  0.08851075, -0.06652325, ...,  0.0138923 ,
          0.1317227 , -0.30160534],
        [-0.36811373, -0.0506771 , -0.60264564, ..., -0.23227769,
          0.3273818 , -0.6825447 ],
        [-0.64091253, -0.10468782, -0.11663467, ...,  0.01066983,
          0.12490633, -1.0322313 ],
        ...,
        [-0.1554488 , -0.39847517,  0.10168535, ...,  0.44280142,
          0.3926771 , -0.31622615],
        [-0.6501855 , -0.06406005,  0.3790466 , ..., -0.08195392,
          0.08189432, -0.502046  ],
        [-0.50222695, -0.01534684,  0.42225617, ..., -0.01777458,
          0.26349908, -0.39077672]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[ 1.92427158e-01,  4.55225781e-02,  1.70830116e-01,
        -1.12610385e-01, -1.04626501e-03,  3.32511365e-01,
         2.24649578e-01,  2.04148144e-01, -2.92777032e-01,
         3.443